### PR TITLE
Start testing Normalizr

### PR DESCRIPTION
**Pull request by feinsteinben**
New test/ dir was added, with some basic tests in it.

New tests:
- basic tests of URL_REGEX, EMAIL_REGEX.
- more tests can be easily add using the same pattern.

It's suggested to start using continuous integration. A basic config file for TravisCI is also included.

### CODE REVIEW

**Comment by davidmogar** [comment]
Great PR @feinsteinben,

I'll accept it for sure but I'll wait for #8 so normalizr can have support for Python 2. I also have a couple of comments for your other PR that I'll write eventually ^^

Thank you,
David

**Comment by davidmogar** [comment]
As I commented in #9 would be nice if you can change the format of your commit messages. Me and my OCD :wink:

**Comment by feinsteinben** [comment]
Fixed it :-)

**Comment by feinsteinben** [comment]
Added several more tests. @davidmogar

**Comment by feinsteinben** [comment]
Hi @davidmogar ,

I found a wrong test-case and fixed it. The fixed commit is in the same branch as the pull-request.

Sorry for the trouble,
Ben.

**Comment by davidmogar** [comment]
Yeah, I suppose it's the one I wrote in #16. I fixed on my local branch. I'll push it now. Otherwise you would have to open a new pull request as this one is already closed ;)

**Pull request merged**
